// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Ki-F9IK5eWA5WIa2AjNsKt8L57ofzXg',
    appId: '1:467288748739:web:26e7face6d50dc20bca876',
    messagingSenderId: '467288748739',
    projectId: 'edudash-3e2d9',
    authDomain: 'edudash-3e2d9.firebaseapp.com',
    storageBucket: 'edudash-3e2d9.firebasestorage.app',
    measurementId: 'G-8RCC7PV9P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhnm1nO8HtFvFpEd7xZ1vyp8og6t32S68',
    appId: '1:467288748739:android:a43ca5e09504a0cabca876',
    messagingSenderId: '467288748739',
    projectId: 'edudash-3e2d9',
    storageBucket: 'edudash-3e2d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYGdGfKLE4TjfkHWj74nmDndBRCAYIgwo',
    appId: '1:467288748739:ios:87cceefe2884f74abca876',
    messagingSenderId: '467288748739',
    projectId: 'edudash-3e2d9',
    storageBucket: 'edudash-3e2d9.firebasestorage.app',
    iosClientId: '467288748739-n767orornv482hd1ktec4m5g8jnr34lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.edudashAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYGdGfKLE4TjfkHWj74nmDndBRCAYIgwo',
    appId: '1:467288748739:ios:87cceefe2884f74abca876',
    messagingSenderId: '467288748739',
    projectId: 'edudash-3e2d9',
    storageBucket: 'edudash-3e2d9.firebasestorage.app',
    iosClientId: '467288748739-n767orornv482hd1ktec4m5g8jnr34lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.edudashAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Ki-F9IK5eWA5WIa2AjNsKt8L57ofzXg',
    appId: '1:467288748739:web:b3bb479c6d3224fbbca876',
    messagingSenderId: '467288748739',
    projectId: 'edudash-3e2d9',
    authDomain: 'edudash-3e2d9.firebaseapp.com',
    storageBucket: 'edudash-3e2d9.firebasestorage.app',
    measurementId: 'G-42LENF6VQ5',
  );
}
